[tool.poetry]
name = "refactored-spoon"
version = "0.1.0"
description = "Directory de restaurants"
authors = ["Albert Ferran Casas <albert.ferran@gmail.com>"]
license = "LICENSE"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
Flask = "3.0.3"
flask-sqlalchemy = "3.1.1"
flask-minify = "0.48"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
