"""add restaurant tables

Revision ID: cc746199efcb
Revises: a47fb7609d8a
Create Date: 2024-09-08 12:51:18.010655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc746199efcb'
down_revision = 'a47fb7609d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_name'), ['name'], unique=True)

    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_name'), ['name'], unique=True)

    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_province_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_province_region_id'), ['region_id'], unique=False)

    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_city_province_id'), ['province_id'], unique=False)

    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurant_province_id'), ['province_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_region_id'), ['region_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_region_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_province_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_name'))
        batch_op.drop_index(batch_op.f('ix_restaurant_country_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_city_id'))

    op.drop_table('restaurant')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_province_id'))
        batch_op.drop_index(batch_op.f('ix_city_name'))

    op.drop_table('city')
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_province_region_id'))
        batch_op.drop_index(batch_op.f('ix_province_name'))

    op.drop_table('province')
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_name'))
        batch_op.drop_index(batch_op.f('ix_region_country_id'))

    op.drop_table('region')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_name'))

    op.drop_table('country')
    # ### end Alembic commands ###
